# Generated by Django 2.1.5 on 2019-12-08 09:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cost',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 9, 32, 10, 892255, tzinfo=utc), verbose_name='date_pulished'),
        ),
    ]
