# Generated by Django 2.1.5 on 2019-12-08 10:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsapp', '0003_auto_20191208_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 10, 36, 12, 161671, tzinfo=utc), verbose_name='date_pulished'),
        ),
    ]
