# Generated by Django 2.1.5 on 2019-12-08 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsapp', '0004_auto_20191208_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 12, 43, 33, 285725, tzinfo=utc), verbose_name='date_pulished'),
        ),
    ]
