# Generated by Django 2.2.8 on 2019-12-08 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsapp', '0005_auto_20191208_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 13, 56, 1, 569210, tzinfo=utc), verbose_name='date_pulished'),
        ),
    ]
