# Generated by Django 2.2.8 on 2019-12-08 17:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fieldsapp', '0007_auto_20191208_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 17, 14, 49, 885369, tzinfo=utc), verbose_name='date_pulished'),
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('avatar2', models.ImageField(upload_to='', verbose_name='Фото')),
                ('avatar3', models.ImageField(upload_to='', verbose_name='Фото')),
                ('body', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание поля')),
                ('address', models.CharField(blank=True, max_length=60, null=True, verbose_name='адрес')),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, verbose_name='номер')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Город')),
                ('pole', models.CharField(choices=[['m', 'Крытый'], ['f', 'Не крытый']], default='m', max_length=10, verbose_name='Полe')),
                ('status', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
