# Generated by Django 2.2.8 on 2019-12-08 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsapp', '0008_auto_20191208_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover2',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 17, 30, 29, 415495, tzinfo=utc), verbose_name='date_pulished'),
        ),
        migrations.DeleteModel(
            name='Fields',
        ),
    ]
