# Generated by Django 2.2.8 on 2019-12-08 17:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsapp', '0009_auto_20191208_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='statuss',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 17, 32, 46, 267738, tzinfo=utc), verbose_name='date_pulished'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
